version: "3.9"  # optional since v1.27.0
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    networks:
      - main-network
  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
      - 5432
    networks:
      - main-network
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: pdp_coax
    volumes:
      - pgReportData:/var/lib/postgresql/data
  api:
    image: pdp-coax-middle-be
    container_name: pdp-coax-middle-be
    expose:
      - 8080
    networks:
      - main-network
    depends_on:
      - redis
      - postgres
    environment:
      EXPRESS_APP_REDIS_HOST: redis
      EXPRESS_APP_DB_HOST: postgres
  next-js:
    image: pdp-coax-middle-fe
    container_name: next-js-fe
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - main-network
    environment:
      NEXT_PUBLIC_APP_HOST: api:8080
networks:
  main-network:
    driver: bridge

volumes:
  pgReportData:
    driver: local

