version: "3.9"  # optional since v1.27.0
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    networks:
      - main-network
  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
      - 5432
    networks:
      - main-network
    env_file:
      - .env
    volumes:
      - pgReportData:/var/lib/postgresql/data
  api:
    image: pdp-coax-middle-be
    container_name: pdp-coax-middle-be
    ports:
      - 8080:8080
    networks:
      - main-network
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
  next-js:
    image: pdp-coax-middle-fe
    container_name: next-js-fe
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - main-network
    env_file:
      - .env
networks:
  main-network:
    driver: bridge

volumes:
  pgReportData:
    driver: local
